### ISSUE TITLE
importError and no python package created

### ISSUE THREAD

**Issue by odemangeon** [nespinoza/flicker-noise#1]
I tried to install the flicker-noise module as described in the readme, everything seems to go well according to the prints in the terminal.
1. It looks like the "python setup.py build" is done but not the "python setup.py install".
So as soon as I cd outside the flicker-noise folder all imports fail.
2. When I am inside the flicker-noise folder and tried to import any of the module within python I get this importError:

```
$ python2.7
Python 2.7.10 (default, Oct 23 2015, 18:05:06)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import FWT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(./FWT.so, 2): Symbol not found: _Py_InitModule
  Referenced from: ./FWT.so
  Expected in: dynamic lookup
```

When I launch the "python setup.py build" directly from the terminal, I get this warning that could be related to the importError 

```
FWT.c:196:9: warning: implicit declaration of function 'Py_InitModule' [-Wimplicit-function-declaration]
  (void) Py_InitModule("FWT", FWTMethods);
```

**Comment by nespinoza** [comment]
Hi! Thanks for reporting this. First of all, there is no need to run "python setup.py install". You just have to run "python install.py" and the install.py file will take care of everything (which basically generates all the executables).

If you want to import the FWT library, you have to move the FWT.so file created with the install.py file (inside the WaveletCode folder) around _or_ add the path where this file is to your code in order tu use it (i.e., sys.path.append('folder')). 

If you did the above and it still doesn't work, can you please share your operating system and Python version? Also, a description of every step that you do in order to run your commands will be optimal (considering everything you do since you clone the repo).

Best

**Comment by nespinoza** [comment]
I suppose this solved the issue, so I'm closing it. If you have further problems please, let me know.
